### ISSUE TITLE
Goto definition

### ISSUE THREAD

**Issue by minkir014** [philippeFernandez/adagnat#1]
Great work But can you support goto definition? It's not too hard after this great work.

**Comment by philippeFernandez** [comment]
Goto is **the bad** but is already implemented ;)
but OK, Label is not highlighted. .tmlanguage syntax definition may have to be udated :/
Please, refer to README.md for .tmlanguage syntax definition link.

(here, I just bundled these other works for my needs : ) )

```
<<Sort>>
for I in 1 .. N-1 loop
   if A(I) > A(I+1) then
      Exchange(A(I), A(I+1));
      goto Sort;
   end if;
end loop;
```
![image](https://user-images.githubusercontent.com/11314461/59156810-b0ace780-8aa1-11e9-861e-da87267acdd4.png)

**Comment by philippeFernandez** [comment]
dependencies stil have to be updated.

**Comment by minkir014** [comment]
Does this pull request https://github.com/philippeFernandez/adagnat/pull/2 updates dependencies?
And what do you mean by      
> **the bad**
